# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Lint
      - run: yarn lint

      # Build
      - run: yarn build

      # Cache for deployment
      - save_cache:
          paths:
            - build
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  # Deployment job
  deploy:
    docker:
      - image: circleci/node:11
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a3:16:64:81:e4:5d:2b:11:09:af:70:79:f3:a3:7a:4e"
      - run: |
          git config --global user.email "cibuild@niklaskorz.de"
          git config --global user.name "CI Build"
      - run: sudo npm install -g gh-pages
      - restore_cache:
          keys:
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: gh-pages --dotfiles --message \"[skip ci] Updates\" --dist build

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
